let express = require('express')
let router = express.Router()
let taller = require('../controller/Taller/taller.controller')
let mdAunt = require('../middleware/middleware-authentication')

/* uso de middleware */
router.use(mdAunt.api_key)
router.use(mdAunt.content_type)
    /* uso de middleware */

router.post('/obtenerUsuarios/', taller.obtenerUsuarios)
router.post('/obtenerListaClientes/', taller.obtenerListaClientes)
router.post('/actualizarContacto/', taller.actualizarContacto)
router.post('/validarCedulaContacto/', taller.validarCedulaContacto)
router.post('/perfilarContacto/', taller.perfilarContacto)
router.post('/ObtenerListaTalleresCreadosAws/', taller.ObtenerListaTalleresCreadosAws)
router.post('/generarActualizacionClienteCreadoAws/', taller.generarActualizacionClienteCreadoAws)
router.post('/obtenerListaContactos/', taller.obtenerListaContactos)
router.post('/obtenerContacto/', taller.obtenerContacto)
router.post('/obtenerCliente/', taller.obtenerCliente)
router.post('/actualizarCliente/', taller.actualizarCliente)
router.post('/obtenerCiudadesClientesRegistrados/', taller.obtenerCiudadesClientesRegistrados)
router.post('/obtenerSucursalesClientesRegistrados/', taller.obtenerSucursalesClientesRegistrados)
router.get('/getPaises', taller.getPaises)
router.post('/getDepartamentos', taller.getDepartamentos)
router.post('/getMunicipios', taller.getMunicipios)
router.post('/obtenerClientesNombreRTN', taller.obtenerClientesNombreRTN)
router.post('/obtenerClientePadre',taller.obtenerClientePadre)
// router.post('/getSucursalesListadotiendas/', taller.getSucursalesListadotiendas)



router.post('/GetEstadisticasTalleres/', taller.GetEstadisticasTalleres)
router.post('/GetEstadisticasTalleres_v2/', taller.GetEstadisticasTalleres_v2)
router.post('/GetEntregaTarjetasPendientes/', taller.GetEntregaTarjetasPendientes)
router.post('/GetTarjetasEntregadas/', taller.GetTarjetasEntregadas)
router.post('/GetListaTalleresVerificacion/', taller.GetListaTalleresVerificacion)
router.post('/mandarActualizarTalleres/', taller.mandarActualizarTalleres)
router.post('/GetListaCiudades/', taller.GetListaCiudades)
router.post('/IndicadoresTallerLlenarFiltros/', taller.IndicadoresTallerLlenarFiltros)
router.post('/IndicadoresTallerSucursalesMetaActualiza/', taller.IndicadoresTallerSucursalesMetaActualiza)
router.post('/IndicadoresTallerSucursalesMetaDevuelve/', taller.IndicadoresTallerSucursalesMetaDevuelve)
router.post('/IndicadoresTallerIndicadoresInicio/', taller.IndicadoresTallerIndicadoresInicio)
router.post('/IndicadoresTallerFacturacionTotal/', taller.IndicadoresTallerFacturacionTotal)
router.post('/IndicadoresTallerVehiculosTrabajados/', taller.IndicadoresTallerVehiculosTrabajados)
router.post('/IndicadoresTallerVehiculosTrabajadosDiario/', taller.IndicadoresTallerVehiculosTrabajadosDiario)
router.post('/IndicadoresTallerFacturacionTotalHoras/', taller.IndicadoresTallerFacturacionTotalHoras)
router.post('/IndicadoresTallerReclamos/', taller.IndicadoresTallerReclamos)
router.post('/IndicadoresTallerReclamosSistema/', taller.IndicadoresTallerReclamosSistema)
router.post('/IndicadoresTallerReprocesosTecnico/', taller.IndicadoresTallerReprocesosTecnico)
router.post('/IndicadoresTallerReprocesosAsesor/', taller.IndicadoresTallerReprocesosAsesor)
router.post('/IndicadoresTallerCumplimientoTareasDiarias/', taller.IndicadoresTallerCumplimientoTareasDiarias)
router.post('/IndicadoresTallerConfResumenDevuelve/', taller.IndicadoresTallerConfResumenDevuelve)
router.post('/IndicadoresTallerConfResumenActualiza/', taller.IndicadoresTallerConfResumenActualiza)
router.post('/IndicadoresTallerEmpleadosSucursal/', taller.IndicadoresTallerEmpleadosSucursal)
router.post('/actualizarEstadoAprobadoRechazado/', taller.actualizarEstadoAprobadoRechazado)
router.post('/actualizarMecanico/', taller.actualizarMecanico)
router.post('/validarCedulaMecanico/', taller.validarCedulaMecanico)
router.post('/eliminarTaller/', taller.eliminarTaller)
router.post('/obtenerTalleresCustomer/', taller.obtenerTalleresCustomer)
router.post('/obtenerUsuarioApp/', taller.obtenerUsuarioApp)

// Mantenimiento de Usuario

router.post('/getUsuario',  taller.getUsuario)
router.post('/getUsuarioById',  taller.getUsuarioById)
router.post('/createUsuario',  taller.createUsuario)
router.post('/updateUsuario',  taller.updateUsuario)
router.post('/getPaginas', taller.getPaginas)

module.exports = router